apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculator-app
  template:
    metadata:
      labels:
        app: calculator-app
    spec:
      containers:
      - name: calculator-container
        image: 650251692877.dkr.ecr.us-east-1.amazonaws.com/calculator-app:latest
        ports:
        - containerPort: 3000
